name: SpotBugs CI

on:
  workflow_dispatch:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Run SpotBugs
        run: ./gradlew check
      - name: Upload SpotBugs Report
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: test results
          path: build/reports/spotbugs/main.html
      - name: Slack Notification
        if: always()
        run: |
          if [[ ${{ job.status }} == "success" ]]; then
            COLOR="good"
          else
            COLOR="danger"
          fi
        
          jq -n --arg color "${COLOR}" \
          --arg jobLink '<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} | ${{ github.workflow }}>' \
          --arg commit '<${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }} | ${{ github.sha }}>' '{
            attachments: [
              {
                pretext: "${{ secrets.BANANA_TEAM_ID }} \n :github: Test ${{ job.status }} :banana:",
                color: $color,
                fields: [
                  {
                    title: "Actor",
                    value: "'"$GITHUB_ACTOR"'",
                    short: true
                  },
                  {
                    title: "Ref",
                    value: "'"$GITHUB_REF"'",
                    short: true
                  },
                  {
                    title: "Event Name",
                    value: "'"$GITHUB_EVENT_NAME"'",
                    short: true
                  },
                  {
                    title: "Actions URL",
                    value: $jobLink,
                    short: true
                  },
                  {
                    title: "Commit",
                    value: $commit,
                    short: false
                  }
                ]
              }
            ]
          }' | curl ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }} -X POST -H 'Content-Type: application/json' -d @-
